In [32]:
! pip install yfinance
! pip install pandas_datareader

Requirement already satisfied: yfinance in /usr/local/python/3.10.8/lib/python3.10/site-packages (0.2.22)
Requirement already satisfied: pandas>=1.3.0 in /home/codespace/.local/lib/python3.10/site-packages (from yfinance) (2.0.2)
Requirement already satisfied: numpy>=1.16.5 in /home/codespace/.local/lib/python3.10/site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.26 in /home/codespace/.local/lib/python3.10/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/python/3.10.8/lib/python3.10/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/python/3.10.8/lib/python3.10/site-packages (from yfinance) (4.9.2)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/python/3.10.8/lib/python3.10/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /home/codespace/.local/lib/python3.10/site-packages (from yfinance) (2023.3)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/python/3.10.8/lib/python3.10/site-packages (from yfinance) (2.3.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/codespace/.local/lib/python3.10/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/python/3.10.8/lib/python3.10/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /home/codespace/.local/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /home/codespace/.local/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /home/codespace/.local/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.26->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.26->yfinance) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.26->yfinance) (2023.5.7)
Collecting pandas_datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: lxml in /usr/local/python/3.10.8/lib/python3.10/site-packages (from pandas_datareader) (4.9.2)
Requirement already satisfied: pandas>=0.23 in /home/codespace/.local/lib/python3.10/site-packages (from pandas_datareader) (2.0.2)
Requirement already satisfied: requests>=2.19.0 in /home/codespace/.local/lib/python3.10/site-packages (from pandas_datareader) (2.31.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (2023.5.7)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)
Installing collected packages: pandas_datareader
Successfully installed pandas_datareader-0.10.0

In [5]:
import yfinance as yf

msft = yf.Ticker("MSFT")
msft.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'fax': '425 706 7329',
 'website': 'https://www.microsoft.com',
 'industry': 'Software—Infrastructure',
 'industryDisp': 'Software—Infrastructure',
 'sector': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. The company operates in three segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing. The Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, Microsoft Viva, and Skype for Business; Skype, Outlook.com, OneDrive, and LinkedIn; and Dynamics 365, a set of cloud-based and on-premises business solutions for organizations and enterprise divisions. The Intelligent Cloud segment licenses SQL, Windows Servers, Visual Studio, System Center, and related Client Access Licenses; GitHub that provides a collaboration platform and code hosting service for developers; Nuance provides healthcare and enterprise AI solutions; and Azure, a cloud platform. It also offers enterprise support, Microsoft consulting, and nuance professional services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification on Microsoft products. The More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; and Windows Internet of Things. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. Microsoft Corporation was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 221000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 55,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2022,
   'totalPay': 12676750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 63,
   'title': 'Pres & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2022,
   'totalPay': 4655274,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 50,
   'title': 'Exec. VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2022,
   'totalPay': 4637915,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson  Althoff',
   'age': 49,
   'title': 'Exec. VP & Chief Commercial Officer',
   'yearBorn': 1973,
   'fiscalYear': 2022,
   'totalPay': 4428268,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 50,
   'title': 'Exec. VP of Bus. Devel., Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2022,
   'totalPay': 4588876,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 55,
   'title': 'Corp. VP & Chief Accounting Officer',
   'yearBorn': 1967,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 50,
   'title': 'Exec. VP of AI & CTO',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brett  Iversen',
   'title': 'Gen. Mang. of Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Corp. VP for Corp. Communications',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher C. Capossela',
   'age': 52,
   'title': 'Exec. VP & Chief Marketing Officer',
   'yearBorn': 1970,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 3,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 2,
 'overallRisk': 2,
 'governanceEpochDate': 1685577600,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 340.54,
 'open': 339.19,
 'dayLow': 336.571,
 'dayHigh': 340.9,
 'regularMarketPreviousClose': 340.54,
 'regularMarketOpen': 339.19,
 'regularMarketDayLow': 336.571,
 'regularMarketDayHigh': 340.9,
 'dividendRate': 2.72,
 'dividendYield': 0.0083,
 'exDividendDate': 1692144000,
 'payoutRatio': 0.28170002,
 'fiveYearAvgDividendYield': 1.09,
 'beta': 0.927464,
 'trailingPE': 36.618637,
 'forwardPE': 30.866667,
 'volume': 12508692,
 'regularMarketVolume': 12508692,
 'averageVolume': 27327155,
 'averageVolume10days': 22059840,
 'averageDailyVolume10Day': 22059840,
 'bid': 337.8,
 'ask': 337.99,
 'bidSize': 1000,
 'askSize': 900,
 'marketCap': 2513121050624,
 'fiftyTwoWeekLow': 213.43,
 'fiftyTwoWeekHigh': 351.47,
 'priceToSalesTrailing12Months': 12.106117,
 'fiftyDayAverage': 320.7104,
 'twoHundredDayAverage': 267.918,
 'trailingAnnualDividendRate': 2.66,
 'trailingAnnualDividendYield': 0.0078111235,
 'currency': 'USD',
 'enterpriseValue': 2462584143872,
 'profitMargins': 0.33248,
 'floatShares': 7428795636,
 'sharesOutstanding': 7435489792,
 'sharesShort': 44270818,
 'sharesShortPriorMonth': 42337959,
 'sharesShortPreviousMonthDate': 1684108800,
 'dateShortInterest': 1686787200,
 'sharesPercentSharesOut': 0.006,
 'heldPercentInsiders': 0.00052,
 'heldPercentInstitutions': 0.73767,
 'shortRatio': 1.57,
 'shortPercentOfFloat': 0.006,
 'impliedSharesOutstanding': 0,
 'bookValue': 26.178,
 'priceToBook': 12.911223,
 'lastFiscalYearEnd': 1656547200,
 'nextFiscalYearEnd': 1688083200,
 'mostRecentQuarter': 1680220800,
 'earningsQuarterlyGrowth': 0.094,
 'netIncomeToCommon': 69020000256,
 'trailingEps': 9.23,
 'forwardEps': 10.95,
 'pegRatio': 2.89,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 11.863,
 'enterpriseToEbitda': 24.606,
 '52WeekChange': 26.963675,
 'SandP52WeekChange': 15.877687,
 'lastDividendValue': 0.68,
 'lastDividendDate': 1684281600,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 337.99,
 'targetHighPrice': 400.0,
 'targetLowPrice': 232.0,
 'targetMeanPrice': 343.51,
 'targetMedianPrice': 340.0,
 'recommendationMean': 1.8,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 43,
 'totalCash': 104419000320,
 'totalCashPerShare': 14.043,
 'ebitda': 100080001024,
 'totalDebt': 79312003072,
 'quickRatio': 1.655,
 'currentRatio': 1.913,
 'totalRevenue': 207590998016,
 'debtToEquity': 40.739,
 'revenuePerShare': 27.844,
 'returnOnAssets': 0.14829001,
 'returnOnEquity': 0.38601002,
 'grossProfits': 135620000000,
 'freeCashflow': 42964873216,
 'operatingCashflow': 83441000448,
 'earningsGrowth': 0.104,
 'revenueGrowth': 0.071,
 'grossMargins': 0.68522,
 'ebitdaMargins': 0.48209998,
 'operatingMargins': 0.41415,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.4674}

In [6]:
# get historical market data
msft.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-06-05 00:00:00-04:00,335.220001,338.559998,334.660004,335.940002,21307100,0.0,0.0
2023-06-06 00:00:00-04:00,335.329987,335.369995,332.170013,333.679993,20396200,0.0,0.0
2023-06-07 00:00:00-04:00,331.649994,334.489990,322.500000,323.380005,40717100,0.0,0.0
2023-06-08 00:00:00-04:00,323.940002,326.640015,323.350006,325.260010,23277700,0.0,0.0
2023-06-09 00:00:00-04:00,324.989990,329.989990,324.410004,326.790009,22514900,0.0,0.0
2023-06-12 00:00:00-04:00,328.579987,332.100006,325.160004,331.850006,24260300,0.0,0.0
2023-06-13 00:00:00-04:00,334.470001,336.980011,330.390015,334.290009,22951300,0.0,0.0
2023-06-14 00:00:00-04:00,334.339996,339.040009,332.809998,337.339996,26003800,0.0,0.0
2023-06-15 00:00:00-04:00,337.480011,349.839996,337.200012,348.100006,38899100,0.0,0.0
2023-06-16 00:00:00-04:00,351.320007,351.470001,341.950012,342.329987,46533600,0.0,0.0
2023-06-20 00:00:00-04:00,339.309998,342.079987,335.859985,338.049988,26375400,0.0,0.0
2023-06-21 00:00:00-04:00,336.369995,337.730011,332.070007,333.559998,25117800,0.0,0.0
2023-06-22 00:00:00-04:00,334.119995,340.119995,333.339996,339.709991,23556800,0.0,0.0
2023-06-23 00:00:00-04:00,334.359985,337.959991,333.450012,335.019989,23084700,0.0,0.0
2023-06-26 00:00:00-04:00,333.720001,336.109985,328.489990,328.600006,21520600,0.0,0.0
2023-06-27 00:00:00-04:00,331.859985,336.149994,329.299988,334.570007,24354100,0.0,0.0
2023-06-28 00:00:00-04:00,334.660004,337.980011,333.809998,335.850006,20259500,0.0,0.0
2023-06-29 00:00:00-04:00,334.709991,336.109985,332.619995,335.049988,16997000,0.0,0.0
2023-06-30 00:00:00-04:00,337.750000,342.730011,337.200012,340.540009,26823800,0.0,0.0
2023-07-03 00:00:00-04:00,339.190002,340.899994,336.570007,337.989990,12508700,0.0,0.0

In [7]:
# show meta information about the history (requires history() to be called first)
msft.history_metadata

{'currency': 'USD',
 'symbol': 'MSFT',
 'exchangeName': 'NMS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 511108200,
 'regularMarketTime': 1688403605,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 337.99,
 'chartPreviousClose': 335.4,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'end': 1688391000,
   'start': 1688371200,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'end': 1688403600,
   'start': 1688391000,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'end': 1688428800,
   'start': 1688403600,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [11]:
# show actions (dividends, splits, capital gains)
msft.actions
msft.dividends
msft.splits
msft.capital_gains  # only for mutual funds & etfs

[]

In [12]:
# show share count
msft.get_shares_full(start="2022-01-01", end=None)

2022-01-27 00:00:00-05:00    7496869888
2022-02-04 00:00:00-05:00    7800719872
2022-02-05 00:00:00-05:00    7496869888
2022-02-11 00:00:00-05:00    7496869888
2022-03-04 00:00:00-05:00    7605040128
2022-03-05 00:00:00-05:00    7496869888
2022-03-16 00:00:00-04:00    7595310080
2022-03-17 00:00:00-04:00    7496869888
2022-03-28 00:00:00-04:00    7507230208
2022-03-31 00:00:00-04:00    7496869888
2022-04-01 00:00:00-04:00    7631819776
2022-04-02 00:00:00-04:00    7496869888
2022-04-04 00:00:00-04:00    7496869888
2022-04-29 00:00:00-04:00    7479029760
2022-06-09 00:00:00-04:00    7536840192
2022-06-13 00:00:00-04:00    7479029760
2022-07-28 00:00:00-04:00    7464000000
2022-08-01 00:00:00-04:00    7457889792
2022-08-25 00:00:00-04:00    7475469824
2022-08-26 00:00:00-04:00    7457889792
2022-09-01 00:00:00-04:00    7457889792
2022-09-02 00:00:00-04:00    7488540160
2022-09-02 00:00:00-04:00    7457889792
2022-09-10 00:00:00-04:00    7290379776
2022-09-12 00:00:00-04:00    7457889792
2022-09-15 00:00:00-04:00    7451089920
2022-09-15 00:00:00-04:00    7457889792
2022-09-16 00:00:00-04:00    7665780224
2022-09-16 00:00:00-04:00    7457889792
2022-09-17 00:00:00-04:00    7457889792
2022-09-17 00:00:00-04:00    7477389824
2022-10-29 00:00:00-04:00    7454470144
2023-01-04 00:00:00-05:00    7461940224
2023-01-06 00:00:00-05:00    7454470144
2023-01-27 00:00:00-05:00    7443800064
2023-03-08 00:00:00-05:00    7523469824
2023-03-08 00:00:00-05:00    7443800064
2023-03-10 00:00:00-05:00    7443800064
2023-03-10 00:00:00-05:00    7484519936
2023-03-30 00:00:00-04:00    7586610176
2023-04-01 00:00:00-04:00    7443800064
2023-04-01 00:00:00-04:00    7555180032
2023-04-04 00:00:00-04:00    7471529984
2023-04-05 00:00:00-04:00    7443800064
2023-04-06 00:00:00-04:00    7518150144
2023-04-07 00:00:00-04:00    7443800064
2023-04-27 00:00:00-04:00    7435489792
2023-05-04 00:00:00-04:00    7460160000
2023-05-06 00:00:00-04:00    7435489792
2023-05-14 00:00:00-04:00    7515870208
2023-05-16 00:00:00-04:00    7435489792
2023-06-14 00:00:00-04:00    7489030144
2023-06-14 00:00:00-04:00    7435489792
2023-06-23 00:00:00-04:00    7535580160
2023-06-24 00:00:00-04:00    7435489792
dtype: int64

In [13]:
# show financials:
# - income statement
msft.income_stmt

,2022-06-30,2021-06-30,2020-06-30
Tax Effect Of Unusual Items,0.0,0.0,0.0
Tax Rate For Calcs,0.131134,0.138266,0.16
Normalized EBITDA,97843000000.0,81602000000.0,65755000000.0
Total Unusual Items,334000000.0,1303000000.0,28000000.0
Total Unusual Items Excluding Goodwill,334000000.0,1303000000.0,28000000.0
Net Income From Continuing Operation Net Minority Interest,72738000000.0,61271000000.0,44281000000.0
Reconciled Depreciation,14460000000.0,11686000000.0,12796000000.0
Reconciled Cost Of Revenue,62650000000.0,52232000000.0,46078000000.0
EBIT,83383000000.0,69916000000.0,52959000000.0
Net Interest Income,31000000.0,-215000000.0,89000000.0
Interest Expense,2063000000.0,2346000000.0,2591000000.0
Interest Income,2094000000.0,2131000000.0,2680000000.0
Normalized Income,72738000000.0,61271000000.0,44281000000.0
Net Income From Continuing And Discontinued Operation,72738000000.0,61271000000.0,44281000000.0
Total Expenses,114887000000.0,98172000000.0,90056000000.0
Total Operating Income As Reported,83383000000.0,69916000000.0,52959000000.0
Diluted Average Shares,7540000000.0,7608000000.0,7683000000.0
Basic Average Shares,7496000000.0,7547000000.0,7610000000.0
Diluted EPS,9.65,8.05,5.76
Basic EPS,9.7,8.12,5.82
Diluted NI Availto Com Stockholders,72738000000.0,61271000000.0,44281000000.0
Net Income Common Stockholders,72738000000.0,61271000000.0,44281000000.0
Net Income,72738000000.0,61271000000.0,44281000000.0
Net Income Including Noncontrolling Interests,72738000000.0,61271000000.0,44281000000.0
Net Income Continuous Operations,72738000000.0,61271000000.0,44281000000.0
Tax Provision,10978000000.0,9831000000.0,8755000000.0
Pretax Income,83716000000.0,71102000000.0,53036000000.0
Other Income Expense,333000000.0,1186000000.0,77000000.0
Other Non Operating Income Expenses,333000000.0,1186000000.0,77000000.0
Special Income Charges,-101000000.0,NaN,NaN
Write Off,101000000.0,NaN,NaN
Gain On Sale Of Security,435000000.0,1303000000.0,28000000.0
Net Non Operating Interest Income Expense,31000000.0,-215000000.0,89000000.0
Interest Expense Non Operating,2063000000.0,2346000000.0,2591000000.0
Interest Income Non Operating,2094000000.0,2131000000.0,2680000000.0
Operating Income,83383000000.0,69916000000.0,52959000000.0
Operating Expense,52237000000.0,45940000000.0,43978000000.0
Research And Development,24512000000.0,20716000000.0,19269000000.0
Selling General And Administration,27725000000.0,25224000000.0,24709000000.0
Selling And Marketing Expense,21825000000.0,20117000000.0,19598000000.0
General And Administrative Expense,5900000000.0,5107000000.0,5111000000.0
Other Gand A,5900000000.0,5107000000.0,5111000000.0
Gross Profit,135620000000.0,115856000000.0,96937000000.0
Cost Of Revenue,62650000000.0,52232000000.0,46078000000.0
Total Revenue,198270000000.0,168088000000.0,143015000000.0
Operating Revenue,198270000000.0,168088000000.0,143015000000.0

In [14]:
msft.quarterly_income_stmt

,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Tax Effect Of Unusual Items,0.0,0.0,-10640000.0,0.0
Tax Rate For Calcs,0.192917,0.192438,0.19,0.182896
Normalized EBITDA,25901000000.0,24047000000.0,24918000000.0,24513000000.0
Total Unusual Items,162000000.0,-232000000.0,-56000000.0,-80000000.0
Total Unusual Items Excluding Goodwill,162000000.0,-232000000.0,-56000000.0,-80000000.0
Net Income From Continuing Operation Net Minority Interest,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Reconciled Depreciation,3549000000.0,3648000000.0,2790000000.0,3979000000.0
Reconciled Cost Of Revenue,16128000000.0,17488000000.0,15452000000.0,16429000000.0
EBIT,22352000000.0,20399000000.0,22072000000.0,20534000000.0
Net Interest Income,252000000.0,210000000.0,141000000.0,56000000.0
Interest Expense,496000000.0,490000000.0,500000000.0,496000000.0
Interest Income,748000000.0,700000000.0,641000000.0,552000000.0
Normalized Income,18299000000.0,16425000000.0,17601360000.0,16740000000.0
Net Income From Continuing And Discontinued Operation,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Total Expenses,30505000000.0,32348000000.0,28604000000.0,31331000000.0
Total Operating Income As Reported,22352000000.0,20399000000.0,21518000000.0,20534000000.0
Diluted Average Shares,7464000000.0,7473000000.0,7485000000.0,7506000000.0
Basic Average Shares,7441000000.0,7451000000.0,7457000000.0,7474000000.0
Diluted EPS,2.45,2.2,2.35,2.23
Basic EPS,2.46,2.2,2.35,2.24
Diluted NI Availto Com Stockholders,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Net Income Common Stockholders,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Net Income,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Net Income Including Noncontrolling Interests,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Net Income Continuous Operations,18299000000.0,16425000000.0,17556000000.0,16740000000.0
Tax Provision,4374000000.0,3914000000.0,4016000000.0,3747000000.0
Pretax Income,22673000000.0,20339000000.0,21572000000.0,20487000000.0
Other Income Expense,321000000.0,-60000000.0,-87000000.0,-47000000.0
Other Non Operating Income Expenses,321000000.0,-60000000.0,-31000000.0,-47000000.0
Gain On Sale Of Security,162000000.0,-232000000.0,-56000000.0,21000000.0
Net Non Operating Interest Income Expense,252000000.0,210000000.0,141000000.0,56000000.0
Interest Expense Non Operating,496000000.0,490000000.0,500000000.0,496000000.0
Interest Income Non Operating,748000000.0,700000000.0,641000000.0,552000000.0
Operating Income,22352000000.0,20399000000.0,21518000000.0,20534000000.0
Operating Expense,14377000000.0,14860000000.0,13152000000.0,14902000000.0
Research And Development,6984000000.0,6844000000.0,6628000000.0,6849000000.0
Selling General And Administration,7393000000.0,8016000000.0,6524000000.0,8053000000.0
Selling And Marketing Expense,5750000000.0,5679000000.0,5126000000.0,6304000000.0
General And Administrative Expense,1643000000.0,2337000000.0,1398000000.0,1749000000.0
Other Gand A,1643000000.0,2337000000.0,1398000000.0,1749000000.0
Gross Profit,36729000000.0,35259000000.0,34670000000.0,35436000000.0
Cost Of Revenue,16128000000.0,17488000000.0,15452000000.0,16429000000.0
Total Revenue,52857000000.0,52747000000.0,50122000000.0,51865000000.0
Operating Revenue,52857000000.0,52747000000.0,50122000000.0,51865000000.0

In [15]:
# - balance sheet
msft.balance_sheet

,2022-06-30,2021-06-30,2020-06-30
Ordinary Shares Number,7464000000.0,7519000000.0,7571000000.0
Share Issued,7464000000.0,7519000000.0,7571000000.0
Net Debt,35850000000.0,43922000000.0,49751000000.0
Total Debt,61270000000.0,67775000000.0,70998000000.0
Tangible Book Value,87720000000.0,84477000000.0,67915000000.0
...,...,...,...
Cash Cash Equivalents And Short Term Investments,104757000000.0,130334000000.0,136527000000.0
Other Short Term Investments,90826000000.0,116110000000.0,122951000000.0
Cash And Cash Equivalents,13931000000.0,14224000000.0,13576000000.0
Cash Equivalents,5673000000.0,6952000000.0,NaN
Cash Financial,8258000000.0,7272000000.0,NaN

In [16]:
msft.quarterly_balance_sheet

,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Ordinary Shares Number,7437000000.0,7447000000.0,7457000000.0,7464000000.0
Share Issued,7437000000.0,7447000000.0,7457000000.0,7464000000.0
Net Debt,21648000000.0,32470000000.0,25738000000.0,35850000000.0
Total Debt,60522000000.0,60114000000.0,60282000000.0,61270000000.0
Tangible Book Value,116864000000.0,104877000000.0,95299000000.0,87720000000.0
...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,104427000000.0,99508000000.0,107244000000.0,104757000000.0
Other Short Term Investments,77865000000.0,83862000000.0,84360000000.0,90826000000.0
Cash And Cash Equivalents,26562000000.0,15646000000.0,22884000000.0,13931000000.0
Cash Equivalents,18053000000.0,8342000000.0,15647000000.0,5673000000.0
Cash Financial,8509000000.0,7304000000.0,7237000000.0,8258000000.0

In [17]:
# - cash flow statement
msft.cashflow

,2022-06-30,2021-06-30,2020-06-30
Free Cash Flow,65149000000.0,56118000000.0,45234000000.0
Repurchase Of Capital Stock,-32696000000.0,-27385000000.0,-22968000000.0
Repayment Of Debt,-9023000000.0,-3750000000.0,-5518000000.0
Issuance Of Debt,NaN,NaN,0.0
Issuance Of Capital Stock,1841000000.0,1693000000.0,1343000000.0
Capital Expenditure,-23886000000.0,-20622000000.0,-15441000000.0
End Cash Position,13931000000.0,14224000000.0,13576000000.0
Beginning Cash Position,14224000000.0,13576000000.0,11356000000.0
Effect Of Exchange Rate Changes,-141000000.0,-29000000.0,-201000000.0
Changes In Cash,-152000000.0,677000000.0,2421000000.0
Financing Cash Flow,-58876000000.0,-48486000000.0,-46031000000.0
Cash Flow From Continuing Financing Activities,-58876000000.0,-48486000000.0,-46031000000.0
Net Other Financing Charges,-863000000.0,-2523000000.0,-3751000000.0
Cash Dividends Paid,-18135000000.0,-16521000000.0,-15137000000.0
Common Stock Dividend Paid,-18135000000.0,-16521000000.0,-15137000000.0
Net Common Stock Issuance,-30855000000.0,-25692000000.0,-21625000000.0
Common Stock Payments,-32696000000.0,-27385000000.0,-22968000000.0
Common Stock Issuance,1841000000.0,1693000000.0,1343000000.0
Net Issuance Payments Of Debt,-9023000000.0,-3750000000.0,-5518000000.0
Net Short Term Debt Issuance,NaN,NaN,0.0
Net Long Term Debt Issuance,-9023000000.0,-3750000000.0,-5518000000.0
Long Term Debt Payments,-9023000000.0,-3750000000.0,-5518000000.0
Long Term Debt Issuance,NaN,NaN,0.0
Investing Cash Flow,-30311000000.0,-27577000000.0,-12223000000.0
Cash Flow From Continuing Investing Activities,-30311000000.0,-27577000000.0,-12223000000.0
Net Other Investing Changes,-2825000000.0,-922000000.0,-1241000000.0
Net Investment Purchase And Sale,18438000000.0,2876000000.0,6980000000.0
Sale Of Investment,44894000000.0,65800000000.0,84170000000.0
Purchase Of Investment,-26456000000.0,-62924000000.0,-77190000000.0
Net Business Purchase And Sale,-22038000000.0,-8909000000.0,-2521000000.0
Purchase Of Business,-22038000000.0,-8909000000.0,-2521000000.0
Net PPE Purchase And Sale,-23886000000.0,-20622000000.0,-15441000000.0
Purchase Of PPE,-23886000000.0,-20622000000.0,-15441000000.0
Operating Cash Flow,89035000000.0,76740000000.0,60675000000.0
Cash Flow From Continuing Operating Activities,89035000000.0,76740000000.0,60675000000.0
Change In Working Capital,446000000.0,-936000000.0,2148000000.0
Change In Other Working Capital,5805000000.0,2324000000.0,2212000000.0
Change In Other Current Liabilities,3169000000.0,5551000000.0,2694000000.0
Change In Other Current Assets,-3514000000.0,-4391000000.0,-3367000000.0
Change In Payables And Accrued Expense,2943000000.0,2798000000.0,3018000000.0
Change In Payable,2943000000.0,2798000000.0,3018000000.0
Change In Account Payable,2943000000.0,2798000000.0,3018000000.0
Change In Inventory,-1123000000.0,-737000000.0,168000000.0
Change In Receivables,-6834000000.0,-6481000000.0,-2577000000.0
Changes In Account Receivables,-6834000000.0,-6481000000.0,-2577000000.0
Stock Based Compensation,7502000000.0,6118000000.0,5289000000.0
Deferred Tax,-5702000000.0,-150000000.0,-3620000000.0
Deferred Income Tax,-5702000000.0,-150000000.0,-3620000000.0
Depreciation Amortization Depletion,14460000000.0,11686000000.0,12796000000.0
Depreciation And Amortization,14460000000.0,11686000000.0,12796000000.0
Depreciation,14460000000.0,11686000000.0,12796000000.0
Operating Gains Losses,-409000000.0,-1249000000.0,-219000000.0
Gain Loss On Investment Securities,NaN,NaN,-219000000.0
Net Income From Continuing Operations,72738000000.0,61271000000.0,44281000000.0

In [18]:
msft.quarterly_cashflow

,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Free Cash Flow,17834000000.0,4899000000.0,16915000000.0,17758000000.0
Repurchase Of Capital Stock,-5509000000.0,-5459000000.0,-5573000000.0,-8757000000.0
Repayment Of Debt,0.0,-750000000.0,-1000000000.0,0.0
Issuance Of Capital Stock,536000000.0,243000000.0,575000000.0,461000000.0
Capital Expenditure,-6607000000.0,-6274000000.0,-6283000000.0,-6871000000.0
End Cash Position,26562000000.0,15646000000.0,22884000000.0,13931000000.0
Beginning Cash Position,15646000000.0,22884000000.0,13931000000.0,12498000000.0
Effect Of Exchange Rate Changes,29000000.0,88000000.0,-230000000.0,-198000000.0
Changes In Cash,10887000000.0,-7326000000.0,9183000000.0,1631000000.0
Financing Cash Flow,-10290000000.0,-11349000000.0,-10883000000.0,-13269000000.0
Cash Flow From Continuing Financing Activities,-10290000000.0,-11349000000.0,-10883000000.0,-13269000000.0
Net Other Financing Charges,-258000000.0,-317000000.0,-264000000.0,-341000000.0
Cash Dividends Paid,-5059000000.0,-5066000000.0,-4621000000.0,-4632000000.0
Common Stock Dividend Paid,-5059000000.0,-5066000000.0,-4621000000.0,-4632000000.0
Net Common Stock Issuance,-4973000000.0,-5216000000.0,-4998000000.0,-8296000000.0
Common Stock Payments,-5509000000.0,-5459000000.0,-5573000000.0,-8757000000.0
Common Stock Issuance,536000000.0,243000000.0,575000000.0,461000000.0
Net Issuance Payments Of Debt,0.0,-750000000.0,-1000000000.0,0.0
Net Long Term Debt Issuance,0.0,-750000000.0,-1000000000.0,0.0
Long Term Debt Payments,0.0,-750000000.0,-1000000000.0,0.0
Investing Cash Flow,-3264000000.0,-7150000000.0,-3132000000.0,-9729000000.0
Cash Flow From Continuing Investing Activities,-3264000000.0,-7150000000.0,-3132000000.0,-9729000000.0
Net Other Investing Changes,-1686000000.0,-301000000.0,-860000000.0,-1138000000.0
Net Investment Purchase And Sale,5330000000.0,104000000.0,4360000000.0,-457000000.0
Sale Of Investment,14393000000.0,11703000000.0,9373000000.0,4462000000.0
Purchase Of Investment,-9063000000.0,-11599000000.0,-5013000000.0,-4919000000.0
Net Business Purchase And Sale,-301000000.0,-679000000.0,-349000000.0,-1263000000.0
Purchase Of Business,-301000000.0,-679000000.0,-349000000.0,-1263000000.0
Net PPE Purchase And Sale,-6607000000.0,-6274000000.0,-6283000000.0,-6871000000.0
Purchase Of PPE,-6607000000.0,-6274000000.0,-6283000000.0,-6871000000.0
Operating Cash Flow,24441000000.0,11173000000.0,23198000000.0,24629000000.0
Cash Flow From Continuing Operating Activities,24441000000.0,11173000000.0,23198000000.0,24629000000.0
Change In Working Capital,1843000000.0,-10347000000.0,1873000000.0,1473000000.0
Change In Other Working Capital,1233000000.0,-8049000000.0,-2912000000.0,11555000000.0
Change In Other Current Liabilities,1721000000.0,2076000000.0,-3836000000.0,3499000000.0
Change In Other Current Assets,598000000.0,-457000000.0,-998000000.0,-3145000000.0
Change In Payables And Accrued Expense,-407000000.0,-2058000000.0,-1567000000.0,2659000000.0
Change In Payable,-407000000.0,-2058000000.0,-1567000000.0,2659000000.0
Change In Account Payable,-407000000.0,-2058000000.0,-1567000000.0,2659000000.0
Change In Inventory,106000000.0,1305000000.0,-543000000.0,-461000000.0
Change In Receivables,-1408000000.0,-3164000000.0,11729000000.0,-12634000000.0
Changes In Account Receivables,-1408000000.0,-3164000000.0,11729000000.0,-12634000000.0
Stock Based Compensation,2465000000.0,2538000000.0,2192000000.0,1997000000.0
Deferred Tax,-1675000000.0,-1305000000.0,-1191000000.0,283000000.0
Deferred Income Tax,-1675000000.0,-1305000000.0,-1191000000.0,283000000.0
Depreciation Amortization Depletion,3549000000.0,3648000000.0,2790000000.0,3979000000.0
Depreciation And Amortization,3549000000.0,3648000000.0,2790000000.0,3979000000.0
Depreciation,3549000000.0,3648000000.0,2790000000.0,3979000000.0
Operating Gains Losses,-40000000.0,214000000.0,-22000000.0,157000000.0
Net Income From Continuing Operations,18299000000.0,16425000000.0,17556000000.0,16740000000.0

In [19]:
# see `Ticker.get_income_stmt()` for more options

# show holders
msft.major_holders

        0                                      1
0   0.05%        % of Shares Held by All Insider
1  73.77%       % of Shares Held by Institutions
2  73.80%        % of Float Held by Institutions
3    6159  Number of Institutions Holding Shares

In [20]:
msft.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",649516597,2023-03-30,0.0874,219530108277
1,Blackrock Inc.,537573096,2023-03-30,0.0723,181694325467
2,State Street Corporation,292106885,2023-03-30,0.0393,98729203208
3,"FMR, LLC",200523373,2023-03-30,0.0270,67774892882
4,Price (T.Rowe) Associates Inc,166035734,2023-03-30,0.0223,56118416113
5,"Geode Capital Management, LLC",144365760,2023-03-30,0.0194,48794181812
6,Morgan Stanley,120316895,2023-03-30,0.0162,40665906166
7,JP Morgan Chase & Company,94617741,2023-03-30,0.0127,31979849356
8,Capital World Investors,87608980,2023-03-30,0.0118,29610958294
9,Norges Bank Investment Management,86316926,2022-12-30,0.0116,29174256975

In [21]:
msft.mutualfund_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Total Stock Market Index Fund,226594602,2022-12-30,0.0304,76586707317
1,Vanguard 500 Index Fund,172326589,2022-12-30,0.0232,58244662133
2,Fidelity 500 Index Fund,81720092,2023-02-27,0.0110,27620573097
3,SPDR S&P 500 ETF Trust,80591530,2023-03-30,0.0108,27239130437
4,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",75130340,2023-03-30,0.0101,25393302882
5,iShares Core S&P 500 ETF,66532494,2023-02-27,0.0089,22487316997
6,Vanguard Growth Index Fund,62920006,2022-12-30,0.0085,21266332213
7,Vanguard Institutional Index Fund-Institutiona...,52237514,2022-12-30,0.0070,17655756846
8,Growth Fund Of America Inc,41256784,2023-03-30,0.0055,13944380021
9,Vanguard Information Technology Index Fund,34018479,2022-11-29,0.0046,11497905384

In [22]:
# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2024-04-23 06:00:00-04:00           NaN           NaN          NaN
2024-01-22 16:00:00-05:00           NaN           NaN          NaN
2024-01-22 05:00:00-05:00           NaN           NaN          NaN
2023-10-23 06:00:00-04:00           NaN           NaN          NaN
2023-07-24 06:00:00-04:00          2.55           NaN          NaN
2023-04-25 12:00:00-04:00          2.23          2.45       0.0981
2023-01-24 11:00:00-05:00          2.29          2.32       0.0109
2022-10-25 12:00:00-04:00          2.30          2.35       0.0205
2022-07-26 12:00:00-04:00          2.29          2.23      -0.0274
2022-04-26 12:00:00-04:00          2.19          2.22       0.0160
2022-01-25 11:00:00-05:00          2.31          2.48       0.0725
2021-10-26 12:00:00-04:00          2.07          2.27       0.0941

In [23]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

'-'

In [24]:
# show options expirations
msft.options

('2023-07-07',
 '2023-07-14',
 '2023-07-21',
 '2023-07-28',
 '2023-08-04',
 '2023-08-11',
 '2023-08-18',
 '2023-09-15',
 '2023-10-20',
 '2023-11-17',
 '2023-12-15',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-06-21',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-12-19')

In [25]:
# show news
msft.news

[{'uuid': '6fa55a71-2a5c-3c7c-852c-8da7ea2d36ba',
  'title': 'Best Stocks To Buy And Watch Now: Dynatrace Headlines 5 Top Tech Stocks For July 2023',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/6fa55a71-2a5c-3c7c-852c-8da7ea2d36ba/best-stocks-to-buy-and-watch.html',
  'providerPublishTime': 1688519729,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/YT.cwQLk4qEhyB3Bo5nmvw--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/2c5e2f23a6ddb52972e092492f32a3c0',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/GA7cp4_u3IS0F6Kabd.tkw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/2c5e2f23a6ddb52972e092492f32a3c0',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT']},
 {'uuid': '429ecd58-3d4a-3ddc-a912-7f5d8b765eea',
  'title': 'US to Curb China Access to Cloud Services Like Amazon, WSJ Says',
  'publisher': 'Bloomberg',
  'link': 'https://finance.yahoo.com/news/us-curb-china-access-cloud-045126788.html',
  'providerPublishTime': 1688503426,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ptZpZIKZ_8D0uGJeys6Kxg--~B/aD0xMzM1O3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/bloomberg_technology_68/f6691a828753af17496cc8e4ef45240c',
     'width': 2000,
     'height': 1335,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/U68d8iuIg5l0J_InC8T8pw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_technology_68/f6691a828753af17496cc8e4ef45240c',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AMZN', 'MSFT']},
 {'uuid': '914ad5b6-e2b7-35d8-b8f5-04d30d5cccc9',
  'title': 'U.S. Aims To Restrict China Access To Cloud-Computing Services From Amazon, Microsoft, Google',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/914ad5b6-e2b7-35d8-b8f5-04d30d5cccc9/u.s.-aims-to-restrict-china.html',
  'providerPublishTime': 1688500042,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/_sS53bm3etXh6ToAur5CnQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/239e6b5fd03a9aecd6164bcb54d42cbc',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/npUywZeDiITpk7daBhTP4Q--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/239e6b5fd03a9aecd6164bcb54d42cbc',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOGL', 'MSFT', 'NVDA', 'AMZN']},
 {'uuid': '5b29fd78-8d77-39fd-83ae-330133fcb1e1',
  'title': 'U.S. Looks to Restrict China’s Access to Cloud Computing to Protect Advanced Technology',
  'publisher': 'The Wall Street Journal',
  'link': 'https://finance.yahoo.com/m/5b29fd78-8d77-39fd-83ae-330133fcb1e1/u.s.-looks-to-restrict.html',
  'providerPublishTime': 1688495460,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/trrWoSfsxgnVoPqVnOBcGg--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/d95cbe9ecb645780bc87729c4f88bf6e',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/Rax_E7_CK2QNkxw08O.waw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/d95cbe9ecb645780bc87729c4f88bf6e',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'NVDA', 'AMZN']},
 {'uuid': '7406006b-e725-3e12-ae99-073e8f9a81ab',
  'title': '12 Easiest Programming Languages for Kids',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/12-easiest-programming-languages-kids-130254323.html',
  'providerPublishTime': 1688475774,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/UuKXn4VicysncumGTZu7ig--~B/aD01NjU7dz04NDg7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/insidermonkey.com/f403467a3583480b84fd4d733b37e9e7',
     'width': 848,
     'height': 565,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/X1wjuoBJCVyjweqthy_HEQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/f403467a3583480b84fd4d733b37e9e7',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL', 'GOOGL', 'MSFT']},
 {'uuid': 'c406c0fa-02c4-3e5f-995c-f6b01ade05ff',
  'title': 'The U.S.-China Tech War Just Intensified. Why Microsoft and Amazon Are at Risk.',
  'publisher': 'Barrons.com',
  'link': 'https://finance.yahoo.com/m/c406c0fa-02c4-3e5f-995c-f6b01ade05ff/the-u.s.-china-tech-war-just.html',
  'providerPublishTime': 1688464200,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/fCJmsolvJvCjo7nuI5U_4w--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/a50d55909e327f5d18a25049c0a3b86a',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/iqTHsM5_5ZKLKq6VPv3h0w--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/a50d55909e327f5d18a25049c0a3b86a',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AMZN', 'MSFT']},
 {'uuid': '0d0b38a7-052c-3853-9b1f-2fbc3c0508fd',
  'title': 'Prediction: 10 Stocks That Will Have Trillion-Dollar Valuations by 2035',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/0d0b38a7-052c-3853-9b1f-2fbc3c0508fd/prediction%3A-10-stocks-that.html',
  'providerPublishTime': 1688462460,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/evn4.FLjserfm59vpOPriw--~B/aD0xNTE0O3c9MTk3OTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/2b29e8cdba65c322569186c1d6a23a71',
     'width': 1979,
     'height': 1514,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/sHq_gHql_wwBxeJPluZW8Q--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/2b29e8cdba65c322569186c1d6a23a71',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['V',
   'PYPL',
   'MSFT',
   'AAPL',
   'GOOGL',
   'META',
   'AMZN',
   'MA',
   'UNH']},
 {'uuid': '8e467a02-deb7-302a-8cf5-96bec7e1c980',
  'title': "Apple among 7 big techs to face tougher EU rules after being rated 'gatekeeper'",
  'publisher': 'Reuters',
  'link': 'https://finance.yahoo.com/news/amazon-google-apple-meta-microsoft-064729247.html',
  'providerPublishTime': 1688453249,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/S.Uhekl4i3IVX59xoga2TQ--~B/aD0xMzIwO3c9MTk4MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-06/bdc7d9a0-1a6e-11ee-b77f-d2fca3bbc49c',
     'width': 1980,
     'height': 1320,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/IIZe.T_4EdgGwME8sT_Zzw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2023-06/bdc7d9a0-1a6e-11ee-b77f-d2fca3bbc49c',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOGL', 'AAPL', 'MSFT']}]

In [30]:
# get option chain for specific expiration
msft.option_chain('2023-07-14')
# data available via: opt.calls, opt.puts

Options(calls=         contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0   MSFT230714C00180000 2023-06-08 16:48:41+00:00   180.0     146.34  156.80
1   MSFT230714C00200000 2023-06-15 14:14:27+00:00   200.0     143.80  136.90
2   MSFT230714C00220000 2023-06-15 16:09:09+00:00   220.0     126.23  117.00
3   MSFT230714C00230000 2023-07-03 16:29:21+00:00   230.0     108.16  107.30
4   MSFT230714C00240000 2023-06-30 19:59:58+00:00   240.0     100.80   97.30
5   MSFT230714C00245000 2023-06-30 19:10:41+00:00   245.0      95.98   91.90
6   MSFT230714C00250000 2023-07-03 16:56:38+00:00   250.0      88.93   87.00
7   MSFT230714C00255000 2023-06-28 16:51:15+00:00   255.0      81.03   83.05
8   MSFT230714C00260000 2023-06-30 19:39:36+00:00   260.0      81.77   77.30
9   MSFT230714C00265000 2023-06-30 17:44:15+00:00   265.0      76.17   72.15
10  MSFT230714C00270000 2023-06-29 15:21:54+00:00   270.0      66.22   67.15
11  MSFT230714C00275000 2023-07-03 14:20:31+00:00   275.0      64.55   62.65
12  MSFT230714C00280000 2023-06-14 18:43:58+00:00   280.0      56.10   57.00
13  MSFT230714C00285000 2023-06-30 19:32:39+00:00   285.0      56.47   52.20
14  MSFT230714C00287500 2023-06-30 14:51:50+00:00   287.5      55.20   50.10
15  MSFT230714C00290000 2023-06-30 19:09:48+00:00   290.0      51.18   47.25
16  MSFT230714C00292500 2023-06-29 16:48:06+00:00   292.5      43.25   44.85
17  MSFT230714C00295000 2023-07-03 16:50:00+00:00   295.0      43.15   43.45
18  MSFT230714C00297500 2023-07-03 16:54:40+00:00   297.5      41.25   41.00
19  MSFT230714C00300000 2023-07-03 15:39:08+00:00   300.0      37.82   38.50
20  MSFT230714C00305000 2023-07-03 15:27:13+00:00   305.0      32.45   33.55
21  MSFT230714C00307500 2023-07-03 16:54:40+00:00   307.5      31.35   31.10
22  MSFT230714C00310000 2023-07-03 16:38:03+00:00   310.0      28.08   28.65
23  MSFT230714C00312500 2023-07-03 16:54:40+00:00   312.5      26.45   26.20
24  MSFT230714C00315000 2023-07-03 16:39:43+00:00   315.0      23.39   23.75
25  MSFT230714C00317500 2023-07-03 16:54:40+00:00   317.5      21.60   21.35
26  MSFT230714C00320000 2023-07-03 16:21:39+00:00   320.0      18.57   18.95
27  MSFT230714C00322500 2023-07-03 16:39:43+00:00   322.5      16.25   16.65
28  MSFT230714C00325000 2023-07-03 16:54:40+00:00   325.0      14.60   14.40
29  MSFT230714C00327500 2023-07-03 15:11:07+00:00   327.5      11.34   12.25
30  MSFT230714C00330000 2023-07-03 16:47:00+00:00   330.0      10.00   10.20
31  MSFT230714C00332500 2023-07-03 16:56:31+00:00   332.5       8.61    8.35
32  MSFT230714C00335000 2023-07-03 16:59:49+00:00   335.0       6.70    6.65
33  MSFT230714C00337500 2023-07-03 16:59:41+00:00   337.5       5.30    5.20
34  MSFT230714C00340000 2023-07-03 16:59:00+00:00   340.0       4.05    4.00
35  MSFT230714C00342500 2023-07-03 16:56:19+00:00   342.5       3.10    2.99
36  MSFT230714C00345000 2023-07-03 16:58:43+00:00   345.0       2.28    2.18
37  MSFT230714C00347500 2023-07-03 16:57:09+00:00   347.5       1.66    1.57
38  MSFT230714C00350000 2023-07-03 16:59:51+00:00   350.0       1.14    1.11
39  MSFT230714C00352500 2023-07-03 16:58:46+00:00   352.5       0.85    0.79
40  MSFT230714C00355000 2023-07-03 16:55:17+00:00   355.0       0.60    0.56
41  MSFT230714C00357500 2023-07-03 16:58:45+00:00   357.5       0.44    0.40
42  MSFT230714C00360000 2023-07-03 16:54:20+00:00   360.0       0.32    0.29
43  MSFT230714C00362500 2023-07-03 16:50:05+00:00   362.5       0.23    0.21
44  MSFT230714C00365000 2023-07-03 16:32:16+00:00   365.0       0.16    0.16
45  MSFT230714C00370000 2023-07-03 16:27:38+00:00   370.0       0.10    0.09
46  MSFT230714C00375000 2023-07-03 16:06:33+00:00   375.0       0.07    0.05
47  MSFT230714C00380000 2023-07-03 16:09:17+00:00   380.0       0.05    0.03
48  MSFT230714C00385000 2023-07-03 14:21:58+00:00   385.0       0.05    0.03
49  MSFT230714C00390000 2023-07-03 16:40:16+00:00   390.0       0.03    0.01
50  MSFT230714C00395000 2023-07-03 14:05:36+00:00   395.0       0.02    0.01
51  MSFT230714C00400000 2023-07-03 14:48:18+00:00   400.0       0.02    0.00
52  MSFT230714C00405000 2023-07-03 16:58:53+00:00   405.0       0.01    0.00
53  MSFT230714C00410000 2023-06-30 17:41:33+00:00   410.0       0.02    0.00
54  MSFT230714C00435000 2023-06-30 13:48:08+00:00   435.0       0.01    0.00

       ask    change  percentChange  volume  openInterest  impliedVolatility  \
0   159.40  0.000000       0.000000     NaN             2           1.501956
1   139.40  0.000000       0.000000     NaN             0           1.326175
2   119.55  0.000000       0.000000     2.0             0           1.194340
3   110.10 -5.089996      -4.494478     1.0             2           1.251957
4    99.65  0.000000       0.000000     7.0             0           1.061040
5    94.55  0.000000       0.000000     1.0             2           0.900392
6    89.90 -0.820000      -0.913649     2.0             0           0.942383
7    84.55  0.000000       0.000000     5.0             0           0.983887
8    79.30  0.000000       0.000000     2.0             0           0.784670
9    74.45  0.000000       0.000000     4.0            14           0.735354
10   69.60  0.000000       0.000000     3.0             0           0.710940
11   64.90 -0.919998      -1.405221     1.0             0           0.754885
12   59.50  0.000000       0.000000     4.0             0           0.573246
13   54.75  0.000000       0.000000   138.0             0           0.587895
14   51.80  0.000000       0.000000     3.0             0           0.557133
15   49.90  0.000000       0.000000     1.0             0           0.557866
16   47.30  0.000000       0.000000     NaN             0           0.532231
17   43.65 -2.899998      -6.297498    10.0             0           0.502202
18   41.15 -3.200001      -7.199102     6.0             0           0.493657
19   38.65 -3.549999      -8.581096    19.0             0           0.467779
20   33.70 -4.450001     -12.059622     5.0             0           0.422857
21   31.25  3.350000      11.964287    15.0             0           0.403082
22   28.80 -3.420000     -10.857143    19.0             0           0.382330
23   26.35 -4.049999     -13.278686     1.0             0           0.360846
24   23.90 -3.610001     -13.370373    51.0             0           0.338386
25   21.50 -2.500000     -10.373445     5.0             0           0.319709
26   19.15 -3.630001     -16.351357    28.0             0           0.303474
27   16.80 -3.549999     -17.929290    12.0             0           0.284919
28   14.55 -2.850000     -16.332378    97.0             0           0.270515
29   12.35 -3.910000     -25.639343    25.0             0           0.255501
30   10.35 -2.490000     -19.935947   427.0             0           0.247078
31    8.45 -1.890000     -18.000004    21.0             0           0.237373
32    6.80 -2.110001     -23.950062   594.0             0           0.232552
33    5.30 -1.900000     -26.388884  1061.0             0           0.226448
34    4.10 -1.700000     -29.565216  3342.0          2326           0.225227
35    3.05 -1.400000     -31.111113   471.0             0           0.221810
36    2.22 -1.020000     -30.909092  1464.0             0           0.219795
37    1.60 -0.810000     -32.793526  1134.0             0           0.219856
38    1.14 -0.750000     -39.682540  3876.0             0           0.220833
39    0.82 -0.550000     -39.285710   150.0             0           0.223885
40    0.58 -0.400000     -39.999996   503.0             0           0.226570
41    0.42 -0.430000     -49.425290    63.0             0           0.231209
42    0.31 -0.240000     -42.857143   668.0             0           0.236824
43    0.23 -0.180000     -43.902440    49.0            65           0.242195
44    0.18 -0.170000     -51.515156   644.0             0           0.250007
45    0.11 -0.100000     -50.000000    45.0             0           0.264656
46    0.07 -0.070000     -50.000000    34.0             0           0.279304
47    0.05 -0.030000     -37.499996     3.0             0           0.296882
48    0.04 -0.010000     -16.666664    21.0             0           0.316413
49    0.03 -0.020000     -40.000004    30.0             0           0.333991
50    0.02 -0.020000     -50.000000    29.0            49           0.343757
51    0.02 -0.020000     -50.000000    14.0            89           0.371100
52    0.02 -0.020000     -66.666670     1.0             0           0.394537
53    0.01  0.000000       0.000000     1.0             0           0.390631
54    0.01  0.000000       0.000000     1.0             0           0.500005

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
5         True      REGULAR      USD
6         True      REGULAR      USD
7         True      REGULAR      USD
8         True      REGULAR      USD
9         True      REGULAR      USD
10        True      REGULAR      USD
11        True      REGULAR      USD
12        True      REGULAR      USD
13        True      REGULAR      USD
14        True      REGULAR      USD
15        True      REGULAR      USD
16        True      REGULAR      USD
17        True      REGULAR      USD
18        True      REGULAR      USD
19        True      REGULAR      USD
20        True      REGULAR      USD
21        True      REGULAR      USD
22        True      REGULAR      USD
23        True      REGULAR      USD
24        True      REGULAR      USD
25        True      REGULAR      USD
26        True      REGULAR      USD
27        True      REGULAR      USD
28        True      REGULAR      USD
29        True      REGULAR      USD
30        True      REGULAR      USD
31        True      REGULAR      USD
32        True      REGULAR      USD
33        True      REGULAR      USD
34       False      REGULAR      USD
35       False      REGULAR      USD
36       False      REGULAR      USD
37       False      REGULAR      USD
38       False      REGULAR      USD
39       False      REGULAR      USD
40       False      REGULAR      USD
41       False      REGULAR      USD
42       False      REGULAR      USD
43       False      REGULAR      USD
44       False      REGULAR      USD
45       False      REGULAR      USD
46       False      REGULAR      USD
47       False      REGULAR      USD
48       False      REGULAR      USD
49       False      REGULAR      USD
50       False      REGULAR      USD
51       False      REGULAR      USD
52       False      REGULAR      USD
53       False      REGULAR      USD
54       False      REGULAR      USD  , puts=         contractSymbol             lastTradeDate  strike  lastPrice    bid  \
0   MSFT230714P00200000 2023-06-15 18:17:29+00:00   200.0       0.02   0.00
1   MSFT230714P00215000 2023-06-27 16:46:53+00:00   215.0       0.01   0.00
2   MSFT230714P00220000 2023-06-20 16:21:41+00:00   220.0       0.03   0.00
3   MSFT230714P00230000 2023-06-20 15:38:48+00:00   230.0       0.03   0.00
4   MSFT230714P00235000 2023-06-23 18:07:35+00:00   235.0       0.03   0.00
5   MSFT230714P00240000 2023-06-26 17:10:27+00:00   240.0       0.01   0.00
6   MSFT230714P00245000 2023-06-30 19:59:59+00:00   245.0       0.01   0.00
7   MSFT230714P00250000 2023-07-03 15:18:39+00:00   250.0       0.01   0.00
8   MSFT230714P00255000 2023-06-29 14:11:16+00:00   255.0       0.02   0.00
9   MSFT230714P00260000 2023-06-30 19:32:42+00:00   260.0       0.02   0.00
10  MSFT230714P00265000 2023-07-03 14:47:54+00:00   265.0       0.01   0.01
11  MSFT230714P00270000 2023-07-03 14:30:04+00:00   270.0       0.03   0.01
12  MSFT230714P00275000 2023-07-03 15:38:45+00:00   275.0       0.03   0.02
13  MSFT230714P00280000 2023-07-03 16:44:10+00:00   280.0       0.03   0.02
14  MSFT230714P00282500 2023-06-30 15:48:55+00:00   282.5       0.07   0.03
15  MSFT230714P00285000 2023-07-03 16:52:19+00:00   285.0       0.05   0.03
16  MSFT230714P00287500 2023-06-30 15:52:05+00:00   287.5       0.07   0.04
17  MSFT230714P00290000 2023-07-03 16:24:32+00:00   290.0       0.06   0.05
18  MSFT230714P00292500 2023-07-03 16:24:27+00:00   292.5       0.07   0.06
19  MSFT230714P00295000 2023-07-03 16:57:18+00:00   295.0       0.07   0.07
20  MSFT230714P00297500 2023-07-03 16:35:00+00:00   297.5       0.09   0.08
21  MSFT230714P00300000 2023-07-03 16:44:48+00:00   300.0       0.12   0.10
22  MSFT230714P00305000 2023-07-03 16:54:07+00:00   305.0       0.16   0.15
23  MSFT230714P00307500 2023-07-03 16:51:12+00:00   307.5       0.18   0.17
24  MSFT230714P00310000 2023-07-03 16:54:57+00:00   310.0       0.21   0.21
25  MSFT230714P00312500 2023-07-03 16:41:25+00:00   312.5       0.28   0.26
26  MSFT230714P00315000 2023-07-03 16:54:57+00:00   315.0       0.34   0.32
27  MSFT230714P00317500 2023-07-03 16:58:53+00:00   317.5       0.40   0.40
28  MSFT230714P00320000 2023-07-03 16:58:27+00:00   320.0       0.53   0.52
29  MSFT230714P00322500 2023-07-03 16:58:42+00:00   322.5       0.68   0.69
30  MSFT230714P00325000 2023-07-03 16:59:13+00:00   325.0       0.91   0.92
31  MSFT230714P00327500 2023-07-03 16:59:01+00:00   327.5       1.23   1.25
32  MSFT230714P00330000 2023-07-03 16:59:07+00:00   330.0       1.70   1.72
33  MSFT230714P00332500 2023-07-03 16:53:40+00:00   332.5       2.45   2.35
34  MSFT230714P00335000 2023-07-03 16:54:37+00:00   335.0       3.20   3.15
35  MSFT230714P00337500 2023-07-03 16:57:12+00:00   337.5       4.19   4.20
36  MSFT230714P00340000 2023-07-03 16:58:33+00:00   340.0       5.35   5.45
37  MSFT230714P00342500 2023-07-03 16:55:00+00:00   342.5       6.90   6.95
38  MSFT230714P00345000 2023-07-03 16:43:52+00:00   345.0       9.08   8.65
39  MSFT230714P00347500 2023-07-03 16:05:38+00:00   347.5      10.55  10.55
40  MSFT230714P00350000 2023-07-03 16:59:46+00:00   350.0      12.62  12.60
41  MSFT230714P00352500 2023-07-03 14:02:04+00:00   352.5      13.30  14.85
42  MSFT230714P00355000 2023-07-03 16:35:04+00:00   355.0      17.85  17.15
43  MSFT230714P00357500 2023-07-03 14:49:02+00:00   357.5      20.60  19.55
44  MSFT230714P00360000 2023-07-03 16:33:25+00:00   360.0      23.00  22.00
45  MSFT230714P00362500 2023-07-03 14:10:30+00:00   362.5      22.65  22.90
46  MSFT230714P00365000 2023-07-03 13:54:13+00:00   365.0      24.60  26.85
47  MSFT230714P00370000 2023-06-20 13:56:40+00:00   370.0      30.95  31.30
48  MSFT230714P00380000 2023-06-23 19:50:00+00:00   380.0      44.20  40.95
49  MSFT230714P00385000 2023-06-29 14:39:49+00:00   385.0      50.60  45.90
50  MSFT230714P00425000 2023-06-29 15:41:50+00:00   425.0      89.00  85.35

      ask    change  percentChange  volume  openInterest  impliedVolatility  \
0    0.01  0.000000       0.000000     NaN             0           0.968750
1    0.01  0.000000       0.000000     NaN             0           0.828127
2    0.01  0.000000       0.000000     1.0             0           0.781252
3    0.01  0.000000       0.000000     4.0             0           0.718753
4    0.01  0.000000       0.000000     2.0             0           0.671878
5    0.01  0.000000       0.000000    14.0             0           0.640629
6    0.01  0.000000       0.000000     6.0            45           0.609379
7    0.01  0.000000       0.000000    24.0             0           0.562504
8    0.02  0.000000       0.000000     3.0             0           0.562504
9    0.02  0.000000       0.000000    21.0             0           0.531255
10   0.02 -0.010000     -50.000000     5.0             0           0.511724
11   0.02 -0.010000     -25.000000     2.0             0           0.488286
12   0.03 -0.010000     -25.000000    17.0             0           0.470708
13   0.04 -0.020000     -40.000004    43.0           102           0.447271
14   0.05  0.000000       0.000000     5.0            25           0.439459
15   0.05 -0.030000     -37.499996    37.0             0           0.419928
16   0.06  0.000000       0.000000     2.0             0           0.410162
17   0.07  0.000000       0.000000    66.0             0           0.398444
18   0.08 -0.030000     -30.000002     9.0             0           0.384772
19   0.08 -0.060000     -46.153843    19.0             0           0.365241
20   0.10 -0.030000     -24.999996    61.0             0           0.355475
21   0.11 -0.020000     -14.285716   187.0           678           0.339850
22   0.16 -0.030000     -15.789475   270.0           610           0.316901
23   0.19 -0.050000     -21.739128    28.0             0           0.304206
24   0.22 -0.040000     -16.000002   136.0           609           0.289558
25   0.27 -0.040000     -12.499998    64.0             0           0.277839
26   0.34  0.000000       0.000000   210.0           857           0.267097
27   0.42 -0.010000      -2.439022   118.0             0           0.254646
28   0.54  0.020000       3.921565   371.0             0           0.244148
29   0.71  0.040000       6.250004   165.0             0           0.234871
30   0.94  0.080000       9.638559  2340.0             0           0.225838
31   1.28  0.120000      10.810811  1736.0             0           0.219002
32   1.75  0.200000      13.333337   949.0             0           0.213387
33   2.39  0.510000      26.288658   364.0             0           0.208992
34   3.25  0.600000      23.076930   632.0             0           0.206673
35   4.30  0.890000      26.969702   570.0             0           0.203621
36   5.55  0.900000      20.224722   582.0             0           0.199837
37   7.05  1.450000      26.605510    65.0             0           0.197396
38   8.75  1.830000      25.241379   113.0             0           0.194344
39  10.70  1.480001      16.317535    83.0             0           0.194710
40  12.75  2.320000      22.524270     7.0             0           0.191170
41  15.00 -0.300000      -2.205884     1.0             0           0.193612
42  17.30  2.900001      19.397999    19.0             0           0.191903
43  19.70  4.050001      24.471306    39.0             0           0.195809
44  22.15  3.639999      18.801650    20.0             0           0.204110
45  24.95  1.049999       4.861107    23.0             0           0.276863
46  27.45 -5.299999     -17.725750     8.0             0           0.297614
47  33.35  0.000000       0.000000     4.0             0           0.441656
48  42.95  0.000000       0.000000     1.0             0           0.487066
49  48.15  0.000000       0.000000     NaN             0           0.552006
50  88.00  0.000000       0.000000     NaN             0           0.823732

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
5        False      REGULAR      USD
6        False      REGULAR      USD
7        False      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26       False      REGULAR      USD
27       False      REGULAR      USD
28       False      REGULAR      USD
29       False      REGULAR      USD
30       False      REGULAR      USD
31       False      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34       False      REGULAR      USD

In [34]:
from pandas_datareader import data as pdr

yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-01-03,225.039993,225.830002,223.880005,225.240005,201.337402,91366500
2017-01-04,225.619995,226.750000,225.610001,226.580002,202.535172,78744400
2017-01-05,226.270004,226.580002,225.479996,226.399994,202.374268,78379000
2017-01-06,226.529999,227.750000,225.899994,227.210007,203.098328,71559900
2017-01-09,226.910004,227.070007,226.419998,226.460007,202.427887,46939700
...,...,...,...,...,...,...
2017-04-24,237.179993,237.410004,234.559998,237.169998,212.923660,119209900
2017-04-25,237.910004,238.949997,237.809998,238.550003,214.162582,76698300
2017-04-26,238.509995,239.529999,238.350006,238.399994,214.027893,84702500
2017-04-27,238.770004,238.949997,237.979996,238.600006,214.207474,57410300
2017-04-28,238.899994,238.929993,237.929993,238.080002,213.740616,63532800